# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='作者名称')),
                ('address', models.CharField(max_length=20, verbose_name='作者地址')),
                ('phone', models.CharField(max_length=15, verbose_name='作者联系方式')),
                ('email', models.EmailField(max_length=254, verbose_name='作者邮箱')),
                ('authorinfo', models.TextField(verbose_name='作者简介')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图书名')),
                ('publish_year', models.DateField(max_length=10, verbose_name='图书出版日期')),
                ('publish_add', models.DateTimeField(auto_now_add=True, verbose_name='图书添加日期')),
                ('price', models.FloatField(verbose_name='图书价格')),
                ('stock', models.IntegerField(verbose_name='图书库存')),
                ('status', models.BooleanField(default=True, verbose_name='出版状态:0,未出版 1,已出版')),
                ('author', models.ManyToManyField(to='managerbook.author', verbose_name='图书作者')),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=10, verbose_name='图书章节')),
                ('pages', models.IntegerField(verbose_name='图书页数')),
                ('words', models.IntegerField(verbose_name='图书字数')),
                ('contentinfo', models.TextField(max_length=200, verbose_name='内容简介')),
                ('logo', models.ImageField(null=True, upload_to='', verbose_name='图书封面')),
                ('catalog', models.TextField(max_length=200, verbose_name='图书目录')),
            ],
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='出版社名称')),
                ('address', models.CharField(max_length=20, verbose_name='出版社地址')),
            ],
        ),
        migrations.CreateModel(
            name='type_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typebook', models.CharField(max_length=10, verbose_name='图书类型')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managerbook.detail', verbose_name='图书详情'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerbook.publisher', verbose_name='图书出版社'),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerbook.type_book', verbose_name='图书类型'),
        ),
    ]
