# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-30 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者表', 'verbose_name_plural': '作者表'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书表', 'verbose_name_plural': '图书表'},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': '图书详情表', 'verbose_name_plural': '图书详情表'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': '出版社表', 'verbose_name_plural': '出版社表'},
        ),
    ]
